spring:
    datasource:
        druid:
            url: jdbc:mysql://127.0.0.1:3306/hallo_boxing?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
            username: root
            password: 123456
            connection-properties: config.decrypt=false
            driver-class-name: com.mysql.jdbc.Driver
            initial-size: 1
            max-active: 20
            min-idle: 1
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 'x'
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: false
            max-open-prepared-statements: -1
            stat-view-servlet:
                enabled: true
                allow: 127.0.0.1
            filter:
                config:
                  enabled: true


mybatis:
  config-location: classpath:configuration.xml
  check-config-location: true
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 8080

pi-connect:
  port: 8266